<template>

	<form-field-template :name="name" :label="label" :hint="hint" :required="required" :labelStyle="labelStyle" :isInlineForm="isInlineForm" :tipRule="tipRule"
	:labelLength="labelLength">

	  	<div class="row">

			<ValidationProvider :name="name" :rules="rules" class="row" tag="div" v-model="selectedValue">

				<template v-slot="{ field, errorMessage, meta, classes }">

					<div class="col-md-4 pl-4 c-form-radio" v-for="option in options" :key="option.id">

						<label class="control-label">

							<input type="radio" class="form-check-input" v-model="selectedValue" :value="option" :name="getUniqueName(option.form_identifier)" @change="onInput(selectedValue)" :class="errorMessage ? 'field-danger' : ''">
			  					{{option.label}}
						</label>
					</div>

					<div v-show="errorMessage" class="error-block is-danger col-md-12">{{errorMessage}}</div>
		  		</template>
			</ValidationProvider>
	  	</div>
  	</form-field-template>
</template>

<script>

	import FormFieldTemplate from '../../../components/MiniComponent/FormField/FormFieldTemplate.vue'

	import { boolean } from '../../../helpers/extraLogics';

	export default {

	  	name: 'radio-field',

		/**
		 * Props passed to the component:
		 * - name: The name of the input field. Required.
		 * - label: The label text for the input field. Required.
		 * - hint: Additional hint or description for the input field. Default is an empty string.
		 * - options: Array of options for the input field. Required.
		 * - required: Boolean flag indicating if the input field is required. Default is false.
		 * - onChange: Callback function triggered on value change. Required.
		 * - value: The initial value of the input field. Can be a string or an object. Default is an empty string.
		 * - labelStyle: Custom style object for the label element. Default is an empty object.
		 * - isInlineForm: Boolean flag indicating if the form is inline. Default is false.
		 * - rules: String defining validation rules for the input field. Default is an empty string.
		 * - from: Additional information about the source of the input field. Default is an empty string.
		 * - tipRule: Tip rule for the input field, can be a number or boolean. Default is false.
		 */
	  	props: {
			name: { type: String, required: true },
			label: { type: String, required: true },
			hint: { type: String, default: '' },
			options: { type: Array, required: true },
			required: { type: Boolean, default: false },
			onChange: { type: Function, Required: true },
			value: { type: [String, Object], default: '' },
			labelStyle: { type: Object, default: () => {} },
			isInlineForm: { type: Boolean, default: false },
			rules: { type: String, default: '' },
			from: { type: String, default: '' },
			tipRule : { type : [Number, Boolean], default : false },
			labelLength : { type : [Number, String], default : 500 }
		},

		/**
		 * Data properties of the component:
		 * - selectedValue: The currently selected value of the component. Default is an empty string.
		 */
	  	data: () => {
			return {
				selectedValue: ''
			}
	  	},

		/**
		 * Lifecycle hook called after the component has been mounted:
		 * - Sets the selectedValue based on the provided value prop.
		 */
	  	mounted() {

			this.selectedValue = boolean(this.value) ? this.value : ''
	  	},

		/**
		 * Watches for changes to the value prop:
		 * - Updates the selectedValue when the value prop changes.
		 */
		watch: {

			value(newVal) {

				this.selectedValue = boolean(newVal) ? newVal : ''
			}
		},

	  	methods: {

			/**
			 * Generates a unique name based on an optional ID.
			 * @param {string} id - Optional ID to be included in the unique name.
			 * @returns {string} - A unique name generated by appending the ID and a random number.
			 */
			getUniqueName (id = '') {

				return id + '__' + Math.floor(Math.random() * 100000);
			},

			/**
			 * Handles input events and invokes the onChange callback with the appropriate parameters.
			 * If 'from' prop is provided, invokes onChange with 'value' and 'name' props, else with 'value' and 'label'.
			 * @param {*} value - The value of the input.
			 */
			onInput(value) {

		  		if(this.from){

					this.onChange(value, this.name)

				} else {

					this.onChange(value, this.label)
		  		}
			}
	  	},

	  	components: {

			'form-field-template': FormFieldTemplate,
	  	}
	}
</script>

<style scoped>
  .c-form-radio > label {
    font-weight: 400;
    cursor: pointer;
  }

  .form-radio{
    padding-left: 28px !important;
  }

  .form-check-input{
    margin-left: -1rem;
  }
</style>